### ISSUE TITLE
Can't view a recording

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/node#25]
I don't have any data for what can be an issue here, unfortunately - it just doesn't load.

I'm at my `tsc` exploration, once again - I've been recording it today with success to create [this repro case](https://github.com/RecordReplay/node/issues/23#issuecomment-932280704). But this one has to hit some different paths that make Replay choke:
https://app.replay.io/recording/3423b90a-1ac8-496f-8261-55d964ad2466
https://app.replay.io/recording/71dfc384-e7de-4ec2-b451-f5d15956e1aa

**Comment by jasonLaster** [comment]
@Andarist curious what @bhackett1024 finds, but yeah - it looks like there were some FatalErrors on our end while replaying.

**Comment by bhackett1024** [comment]
It looks like node OOM'ed in the GC when replaying.  I'm not super familiar with V8's GC, but I think the problem is that it was trying to promote an object and couldn't copy it to the old space because of a limit on the maximum size of the old space.  I added an attempted fix and some diagnostics in https://github.com/RecordReplay/node/commit/11b15c652012d2f19677e2a79c9b6e94220da161, so things should be working better in the latest node (run `replay-node --update` to update), and if not we'll have more information to track down what's going wrong.
